type SubServiceName = keyof typeof subServiceNameDict
type RegexDescription = {
    [K in SubServiceName] : RegExp[]
}


export const subServiceNameDict = {
    "Amazon Elastic Compute Cloud running Linux/UNIX":"Linux/UNIX",
    "EBS":"EBS",
    "Bandwidth":"Bandwidth",
    "Elastic Load Balancing - Application":"Application",
    "Amazon Relational Database Service for PostgreSQL":"PostgreSQL",
    "Amazon Relational Database Service Provisioned Storage":"Provisioned Storage",
    "Amazon Simple Storage Service APS1-TimedStorage-ByteHrs":"TimedStorage-ByteHrs",
    "Amazon CloudFront APS1-Lambda-Edge-GB-Second":"Lambda-Edge-GB-Second",
    "AmazonCloudWatch APS1-TimedStorage-ByteHrs":"TimedStorage-ByteHrs",
    "AmazonCloudWatch PutLogEvents":"PutLogEvents",
    "Amazon Elastic Compute Cloud running Linux/UNIX Spot Instances":"Linux/UNIX Spot Instances",
    "Amazon Simple Storage Service APS1-Requests-Tier1":"Requests-Tier1",
    "Amazon CloudWatch":"CloudWatch",
    "Elastic IP Addresses":"Elastic IP Addresses",
    "Amazon Simple Storage Service APS1-Requests-Tier2":"Requests-Tier2",
    "Amazon EC2 Container Registry (ECR) APS1-TimedStorage-ByteHrs":"TimedStorage-ByteHrs",
    "Amazon Route 53 HostedZone":"HostedZone",
    "Amazon Elastic Compute Cloud NatGateway":"NatGateway",
    "Amazon ElastiCache CreateCacheCluster:0002":"CreateCacheCluster:0002",
    "Amazon Elastic Compute Cloud T4GCPUCredits":"T4GCPUCredits",
    "Amazon Relational Database Service Backup Storage":"Backup Storage",
    "Amazon Relational Database Service for Aurora PostgreSQL":"Aurora PostgreSQL",
    "Amazon DynamoDB APS1-TimedPITRStorage-ByteHrs":"TimedPITRStorage-ByteHrs",
    "AWS Key Management Service ap-southeast-1-KMS-Keys":"KMS-Keys",
    "Amazon ElastiCache CreateCacheSnapshot":"CreateCacheSnapshot",
    "Amazon Elastic Container Service APS1-SpotUsage-Fargate-GB-Hours":"SpotUsage-Fargate-GB-Hours",
    "AWS Secrets Manager APS1-AWSSecretsManager-Secret":"AWSSecretsManager-Secret",
    "AWS Secrets Manager APS1-AWSSecretsManagerAPIRequest":"AWSSecretsManagerAPIRequest",
    "Amazon Elastic Container Service APS1-SpotUsage-Fargate-vCPU-Hours:perCPU":"SpotUsage-Fargate-vCPU-Hours:perCPU",
    "AWS Data Transfer APS1-USE1-AWS-Out-Bytes":"APS1-USE1-AWS-Out-Bytes",
    "Amazon Elastic Compute Cloud T3ACPUCredits":"T3ACPUCredits",
    "Amazon DynamoDB APS1-TimedBackupStorage-ByteHrs":"TimedBackupStorage-ByteHrs",
    "Amazon API Gateway ApiGatewayRequest":"ApiGatewayRequest",
    "Amazon DynamoDB PayPerRequestThroughput":"PayPerRequestThroughput",
    "DynamoDB Accelerator (DAX) APS1-NodeUsage:dax.t2.small":"NodeUsage:dax.t2.small",
    "AWS Lambda APS1-Lambda-Provisioned-Concurrency":"Lambda-Provisioned-Concurrency",
    "Amazon Route 53 DNS-Queries":"DNS-Queries",
    "Amazon Registrar RenewDomain":"RenewDomain",
    "AWS Lambda APS1-Lambda-Provisioned-GB-Second":"Lambda-Provisioned-GB-Second",
    "Amazon Managed Blockchain Fabric:Starter":"Fabric:Starter",
    "Amazon Virtual Private Cloud VpcEndpoint":"VpcEndpoint",
    "DynamoDB Accelerator (DAX) APS1-NodeUsage:dax.t3.small":"NodeUsage:dax.t3.small",
    "No Instance Type":"No Instance Type",
    "AWS Lambda APS1-Request":"Request",
    "EC2 Instance Savings Plans":"EC2 Instance",
    "Amazon Elastic Compute Cloud running Red Hat Enterprise Linux":"Red Hat Enterprise Linux",
    "Amazon DynamoDB":"DynamoDB",
    "Amazon ElastiCache CreateCacheCluster:0002 Reserved Instances":"Reserved Instances",
    "Compute Savings Plans":"Compute Savings Plans",
    "DynamoDB Accelerator (DAX) APS1-NodeUsage:dax.t3.medium":"NodeUsage:dax.t3.medium",
    "AWS Lambda APS1-Lambda-GB-Second":"Lambda-GB-Second",
    "Amazon Aurora Storage and I/O":"Aurora Storage and I/O",
    "Amazon Relational Database Service for PostgreSQL Reserved Instances":"PostgreSQL Reserved Instances",
    "Amazon DynamoDB APS1-TimedStorage-ByteHrs":"TimedStorage-ByteHrs",
    "Amazon CloudFront APS1-Requests-OriginShield":"Requests-OriginShield",
    "Amazon Relational Database Service for Aurora PostgreSQL Reserved Instances":"Aurora PostgreSQL Reserved Instances",
    "Elastic Compute Cloud running Linux/UNIX":"Linux/UNIX",
    "AmazonCloudWatch StartQuery":"StartQuery",
    "AWS Cost Explorer CostDataStorage":"CostDataStorage",
    "Amazon Elastic Container Service APS1-Fargate-vCPU-Hours:perCPU":"Fargate-vCPU-Hours:perCPU"
}


export const regexPatternDescription : RegexDescription = {
    "Amazon Elastic Compute Cloud running Linux/UNIX":[/^\$(\d+\.\d+|\d+).*Linux\s(.*)\sInstance/],
    "EBS":[/^\$(\d+\.\d+|\d+).*of\s(.*)\sprovisioned storage/,/^\$(\d+\.\d+|\d+).*of\s(\w+\s\w+\s\w+)/],
    "Bandwidth":[/^\$(\d+\.\d+|\d+).*\/\s(\w+\s\w+\s\w+)/,/^\$(\d+\.\d+|\d+).*-\s(\w+\s\w+\s\w+)/],
    "Elastic Load Balancing - Application":[/^\$(\d+\.\d+|\d+).*(A.*)\s\(/],
    "Amazon Relational Database Service for PostgreSQL":[/^(?:USD|\$)\s(\d+\.\d+|\d+).*db\.(.*)\sinstance/,/^(?:USD|\$)\s(\d+\.\d+|\d+).*of\s(.*)/],
    "Amazon Relational Database Service Provisioned Storage":[/^\$(\d+\.\d+|\d+).*of\s(\w+\s\w+\s\w+)/, /^USD\s(\d+\.\d+|\d+).*of\s(.*)/],
    "Amazon Simple Storage Service APS1-TimedStorage-ByteHrs":[/^\$(\d+\.\d+|\d+).*of\s(.*)$/],
    "Amazon CloudFront APS1-Lambda-Edge-GB-Second":[/^\$(\d+\.\d+|\d+).*for\s(.*)\sin/],
    "AmazonCloudWatch APS1-TimedStorage-ByteHrs":[/^\$(\d+\.\d+|\d+).*of\s(\w+\s\w+)/],
    "AmazonCloudWatch PutLogEvents":[/^\$(\d+\.\d+|\d+).*GB\s(\w+\s\w+\s+\w+)/],
    "Amazon Elastic Compute Cloud running Linux/UNIX Spot Instances":[/^(.*)\sLinux/],
    "Amazon Simple Storage Service APS1-Requests-Tier1":[/^\$(\d+\.\d+|\d+).*per\s(.*)$/],
    "Amazon CloudWatch":[/^\$(\d+\.\d+|\d+).*per\s(\w+)/],
    "Elastic IP Addresses":[/^\$(\d+\.\d+|\d+)\sper\s(\w+\s\w+\s\w+)/],
    "Amazon Simple Storage Service APS1-Requests-Tier2":[/^\$(\d+\.\d+|\d+).*per\s(.*)$/],
    "Amazon EC2 Container Registry (ECR) APS1-TimedStorage-ByteHrs":[/^\$(\d+\.\d+|\d+).*of\s(\w+\s\w+)/],
    "Amazon Route 53 HostedZone":[/^\$(\d+\.\d+|\d+).*per\s(\w+\s\w+)/],
    "Amazon Elastic Compute Cloud NatGateway":[/^\$(\d+\.\d+|\d+).*per\s(\w+\s\w+\s\w+)/],
    "Amazon ElastiCache CreateCacheCluster:0002":[/^\$(\d+\.\d+|\d+).*per\s(\w+\s\w+\s\w+)/],
    "Amazon Elastic Compute Cloud T4GCPUCredits":[/^\$(\d+\.\d+|\d+).*of\s(.*)/],
    "Amazon Relational Database Service Backup Storage":[/^\$(\d+\.\d+|\d+).*per\s(\w+).*of\s(.*)\sexceeding.*running\s(.*)$/,/^USD\s(\d+\.\d+|\d+).*of\s(.*)\sexceeding/],
    "Amazon Relational Database Service for Aurora PostgreSQL":[/^USD\s(\d+\.\d+|\d+).*of\s(.*)\sexceeding/,/^\$\s(\d+\.\d+|\d+).*RDS\s(.*)\sinstance/,/^(?:USD|\$)\s(\d+\.\d+|\d+).*db\.(.*)\sinstance/,/^(?:USD|\$)\s(\d+\.\d+|\d+).*of\s(.*)/],
    "Amazon DynamoDB APS1-TimedPITRStorage-ByteHrs":[/^\$(\d+\.\d+|\d+).*for\s(.*)$/],
    "AWS Key Management Service ap-southeast-1-KMS-Keys":[/^\$(\d+\.\d+|\d+).*per\s(\w+\s\w+\s\w+)/],
    "Amazon ElastiCache CreateCacheSnapshot":[/^\$(\d+\.\d+|\d+).*per\s(\w+).*of\s(.*)\sexceeding/],
    "Amazon Elastic Container Service APS1-SpotUsage-Fargate-GB-Hours":[/^.*-\s(.*)\s-/],
    "AWS Secrets Manager APS1-AWSSecretsManager-Secret":[/^\$(\d+\.\d+|\d+).*per\s(.*)/],
    "AWS Secrets Manager APS1-AWSSecretsManagerAPIRequest":[/^\$(\d+\.\d+|\d+).*per\s(.*)/],
    "Amazon Elastic Container Service APS1-SpotUsage-Fargate-vCPU-Hours:perCPU":[/^.*-\s(.*)\s-/],
    "AWS Data Transfer APS1-USE1-AWS-Out-Bytes":[/^\$(\d+\.\d+|\d+).*\)\s(.*)\sUS.*\((\w+\s\w+)\)/],
    "Amazon Elastic Compute Cloud T3ACPUCredits":[/^\$(\d+\.\d+|\d+).*of\s(.*)/],
    "Amazon DynamoDB APS1-TimedBackupStorage-ByteHrs":[/^\$(\d+\.\d+|\d+).*for\s(.*)$/],
    "Amazon API Gateway ApiGatewayRequest":[/^\$(\d+\.\d+|\d+)\/(.*)\s-/],
    "Amazon DynamoDB PayPerRequestThroughput":[/^\$(\d+\.\d+|\d+)\sper\s(.*)\s\(.*\(/],
    "DynamoDB Accelerator (DAX) APS1-NodeUsage:dax.t2.small":[/^\$(\d+\.\d+|\d+)\sper\s(.*)\s\(/],
    "AWS Lambda APS1-Lambda-Provisioned-Concurrency":[/^.*-\s(.*)\s-/],
    "Amazon Route 53 DNS-Queries":[/^\$(\d+\.\d+|\d+)\sper\s(.*)\sfor/],
    "Amazon Registrar RenewDomain":[/^.*of\s(.*)/],
    "AWS Lambda APS1-Lambda-Provisioned-GB-Second":[/^.*-\s(.*)\s-/],
    "Amazon Managed Blockchain Fabric:Starter":[/^USD(\d+\.\d+|\d+).*for\s(.*)\sin/],
    "Amazon Virtual Private Cloud VpcEndpoint":[/^\$(\d+\.\d+|\d+).*per\s(.*)$/],
    "DynamoDB Accelerator (DAX) APS1-NodeUsage:dax.t3.small":[/^\$(\d+\.\d+|\d+)\sper\s(.*)\s\(.*\(/],
    "No Instance Type":[/^.*-\s(\w+\s\w+)/],
    "AWS Lambda APS1-Request":[/^.*-\s(\w+\s\w+)\s-/],
    "EC2 Instance Savings Plans":[/^USD\s(\d+\.\d+|\d+).*Upfront\s.*\s(\w+\s\w+)\sSavings/],
    "Amazon Elastic Compute Cloud running Red Hat Enterprise Linux":[/^\$(\d+\.\d+|\d+).*RHEL\s(.*)\sInstance/],
    "Amazon DynamoDB":[/^\$(\d+\.\d+|\d+).*for\s(.*)\sbeyond/],
    "Amazon ElastiCache CreateCacheCluster:0002 Reserved Instances":[/^USD\s(\d+\.\d+|\d+).*,(.*)\sinstance/],
    "Compute Savings Plans":[/^(\d+\.\d+|\d+).*\s(\w+\s\w+)$/,/^USD\s(\d+\.\d+|\d+).*\s(\w+\s\w+)\sID:/],
    "DynamoDB Accelerator (DAX) APS1-NodeUsage:dax.t3.medium":[/^\$(\d+\.\d+|\d+)\sper\s(.*)\s\(.*\(/],
    "AWS Lambda APS1-Lambda-GB-Second":[/^.*-\s(.*)\s-/],
    "Amazon Aurora Storage and I/O":[/^USD\s(\d+\.\d+|\d+).*for\s(.*)/],
    "Amazon Relational Database Service for PostgreSQL Reserved Instances":[/.*\s(\w+\s\w+\s\w+):/],
    "Amazon DynamoDB APS1-TimedStorage-ByteHrs":[/^\$(\d+\.\d+|\d+).*of\s(\w+\s\w+)/],
    "Amazon CloudFront APS1-Requests-OriginShield":[/^\$(\d+\.\d+|\d+).*per\s(.*)/],
    "Amazon Relational Database Service for Aurora PostgreSQL Reserved Instances":[/.*\s(\w+\s\w+\s\w+):/],
    "Elastic Compute Cloud running Linux/UNIX":[],
    "AmazonCloudWatch StartQuery":[/^\$(\d+\.\d+|\d+).*\s(\w+\s\w+\s\w+)\sby/],
    "AWS Cost Explorer CostDataStorage":[/^\$(\d+\.\d+|\d+).*of\s(.*)/],
    "Amazon Elastic Container Service APS1-Fargate-vCPU-Hours:perCPU":[/^.*-\s(.*)\s-/]
    
}